// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyyBZr-iVoO7KFcVhXOycN6MQ6oeJ0YK4',
    appId: '1:808470468802:web:aeddad22ba495ce2d3435b',
    messagingSenderId: '808470468802',
    projectId: 'bridgetalk-9310b',
    authDomain: 'bridgetalk-9310b.firebaseapp.com',
    storageBucket: 'bridgetalk-9310b.firebasestorage.app',
    measurementId: 'G-S4P5R6BDB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoHLLYb3c6Mu4pFGQ3deQQyuAUweGShzw',
    appId: '1:808470468802:android:480f8095055e1574d3435b',
    messagingSenderId: '808470468802',
    projectId: 'bridgetalk-9310b',
    storageBucket: 'bridgetalk-9310b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBWA_vIBvDctW9a0NuXAS7Y_4j1GUImqI',
    appId: '1:808470468802:ios:78cf8f3736b1ea6ad3435b',
    messagingSenderId: '808470468802',
    projectId: 'bridgetalk-9310b',
    storageBucket: 'bridgetalk-9310b.firebasestorage.app',
    iosClientId: '808470468802-asrf3ci8dvlm48bs0vilrv04h29l28nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridgetalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBWA_vIBvDctW9a0NuXAS7Y_4j1GUImqI',
    appId: '1:808470468802:ios:78cf8f3736b1ea6ad3435b',
    messagingSenderId: '808470468802',
    projectId: 'bridgetalk-9310b',
    storageBucket: 'bridgetalk-9310b.firebasestorage.app',
    iosClientId: '808470468802-asrf3ci8dvlm48bs0vilrv04h29l28nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridgetalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyyBZr-iVoO7KFcVhXOycN6MQ6oeJ0YK4',
    appId: '1:808470468802:web:31a1340e9b9da8c5d3435b',
    messagingSenderId: '808470468802',
    projectId: 'bridgetalk-9310b',
    authDomain: 'bridgetalk-9310b.firebaseapp.com',
    storageBucket: 'bridgetalk-9310b.firebasestorage.app',
    measurementId: 'G-1YYKHLKB19',
  );

}